### ISSUE TITLE
**A lot of issues**

### ISSUE THREAD

**Issue by justanotherbyte** [FirePlank/FireBot#21]
1) Using `client` as a variable name for your bot
2) Using elephant SQL
3) using Heroku
4) Not subclassing `commands.HelpCommand`
5) Using `httpx` (not really so much of a problem, but `aiohttp` is preferred).
6) Not using the `async` side of `httpx`

I'll leave you with the fun task of finding the other problems yourself.

**Comment by mikeysan** [comment]
I know this is old and hopefully these types of issues are no longer being raised because I find this to be a most unhelpful approach to raising an issue on any project. The point of raising issues is to help the project. I fail to see how this helps anyone.
